$filePath = "c:\Users\abeja\OneDrive\Desktop\Aura\project-frontend\src\pages\admin\Dashboard.tsx"
$lines = Get-Content $filePath
$startLine = 726
$endLine = 2607
$newContent = $lines[0..($startLine-2)]
$newContent += "    const renderContent = () => {"
$newContent += "        const pendingOrdersCount = orders.filter(o => o.status === 'pending').length;"
$newContent += ""
$newContent += "        // Calculate Recent Activity"
$newContent += "        const recentActivity = ["
$newContent += "            ...(orders || []).map(o => ({"
$newContent += "                id: o._id,"
$newContent += "                type: 'order',"
$newContent += "                title: ``New Order: \${o.fullName || 'Guest User'}``,"
$newContent += "                subtitle: ``\${o.items?.length || 0} items • \$$\${(o.total || 0).toFixed(2)}``,"
$newContent += "                time: o.createdAt || new Date().toISOString(),"
$newContent += "                status: o.status || 'pending'"
$newContent += "            })),"
$newContent += "            ...(users || []).map(u => ({"
$newContent += "                id: u._id,"
$newContent += "                type: 'user',"
$newContent += "                title: 'User Registered',"
$newContent += "                subtitle: u.email || 'No email',"
$newContent += "                time: u.createdAt || new Date().toISOString(),"
$newContent += "                status: u.isVerified ? 'verified' : 'pending'"
$newContent += "            }))"
$newContent += "        ].sort((a, b) => new Date(b.time || 0).getTime() - new Date(a.time || 0).getTime()).slice(0, 5);"
$newContent += ""
$newContent += "        switch (activeSection) {"
$newContent += "            case 'addProduct':"
$newContent += "                return ("
$newContent += "                    <ProductManagement"
$newContent += "                        products={products}"
$newContent += "                        inventoryView={inventoryView}"
$newContent += "                        setInventoryView={setInventoryView}"
$newContent += "                        isEditing={isEditing}"
$newContent += "                        setIsEditing={setIsEditing}"
$newContent += "                        newProduct={newProduct}"
$newContent += "                        setNewProduct={setNewProduct}"
$newContent += "                        imagePreviews={imagePreviews}"
$newContent += "                        setImagePreviews={setImagePreviews}"
$newContent += "                        selectedFiles={selectedFiles}"
$newContent += "                        setSelectedFiles={setSelectedFiles}"
$newContent += "                        fileInputRef={fileInputRef}"
$newContent += "                        handleFormSubmit={handleFormSubmit}"
$newContent += "                        startEditing={startEditing}"
$newContent += "                        cancelEditing={cancelEditing}"
$newContent += "                        handleDeleteProduct={handleDeleteProduct}"
$newContent += "                        productsPagination={productsPagination}"
$newContent += "                        setProductPage={setProductPage}"
$newContent += "                        getImageUrl={getImageUrl}"
$newContent += "                        activeDropdownId={activeDropdownId}"
$newContent += "                        setActiveDropdownId={setActiveDropdownId}"
$newContent += "                        categories={categories}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "            case 'orders':"
$newContent += "                return ("
$newContent += "                    <OrderManagement"
$newContent += "                        orders={orders}"
$newContent += "                        ordersPagination={ordersPagination}"
$newContent += "                        setOrderPage={setOrderPage}"
$newContent += "                        searchQuery={searchQuery}"
$newContent += "                        setSearchQuery={setSearchQuery}"
$newContent += "                        orderFilter={orderFilter}"
$newContent += "                        setOrderFilter={setOrderFilter}"
$newContent += "                        orderSort={orderSort}"
$newContent += "                        setOrderSort={setOrderSort}"
$newContent += "                        updateOrderStatus={updateOrderStatus}"
$newContent += "                        handleDeleteOrder={handleDeleteOrder}"
$newContent += "                        activeDropdownId={activeDropdownId}"
$newContent += "                        setActiveDropdownId={setActiveDropdownId}"
$newContent += "                        getStatusConfig={getStatusConfig}"
$newContent += "                        openOrderDetails={(order) => {"
$newContent += "                            setSelectedOrder(order);"
$newContent += "                            setIsOrderModalOpen(true);"
$newContent += "                        }}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "            case 'users':"
$newContent += "                return ("
$newContent += "                    <UserManagement"
$newContent += "                        users={users}"
$newContent += "                        usersPagination={usersPagination}"
$newContent += "                        setUserPage={setUserPage}"
$newContent += "                        searchQuery={searchQuery}"
$newContent += "                        setSearchQuery={setSearchQuery}"
$newContent += "                        handleUpdateUserRole={handleUpdateUserRole}"
$newContent += "                        activeDropdownId={activeDropdownId}"
$newContent += "                        setActiveDropdownId={setActiveDropdownId}"
$newContent += "                        getRoleConfig={getRoleConfig}"
$newContent += "                        updatingRoleUserId={updatingRoleUserId}"
$newContent += "                        isFullAdmin={isFullAdmin}"
$newContent += "                        handleDeleteUser={(id) => setConfirmation({"
$newContent += "                            isOpen: true,"
$newContent += "                            type: 'deleteUser',"
$newContent += "                            id,"
$newContent += "                            title: 'Delete User',"
$newContent += "                            message: 'Are you sure you want to delete this user? This action cannot be undone.',"
$newContent += "                            isDestructive: true"
$newContent += "                        })}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "            case 'reviews':"
$newContent += "                return ("
$newContent += "                    <ReviewManagement"
$newContent += "                        reviews={reviews}"
$newContent += "                        handleDeleteReview={(id) => setConfirmation({"
$newContent += "                            isOpen: true,"
$newContent += "                            type: 'deleteReview',"
$newContent += "                            id,"
$newContent += "                            title: 'Delete Review',"
$newContent += "                            message: 'Are you sure you want to delete this review?',"
$newContent += "                            isDestructive: true"
$newContent += "                        })}"
$newContent += "                        getImageUrl={getImageUrl}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "            case 'coupons':"
$newContent += "                return ("
$newContent += "                    <CouponManagement"
$newContent += "                        coupons={coupons}"
$newContent += "                        handleDeleteCoupon={(id) => setConfirmation({"
$newContent += "                            isOpen: true,"
$newContent += "                            type: 'deleteCoupon',"
$newContent += "                            id,"
$newContent += "                            title: 'Delete Coupon',"
$newContent += "                            message: 'Are you sure you want to delete this coupon?',"
$newContent += "                            isDestructive: true"
$newContent += "                        })}"
$newContent += "                        fetchData={fetchData}"
$newContent += "                        authHeader={authHeader}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "            case 'analytics':"
$newContent += "                return ("
$newContent += "                    <DashboardStats"
$newContent += "                        stats={stats}"
$newContent += "                        fetchData={fetchData}"
$newContent += "                        setStats={setStats}"
$newContent += "                        timeRange={timeRange}"
$newContent += "                        setTimeRange={setTimeRange}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "            default:"
$newContent += "                return ("
$newContent += "                    <DashboardOverview"
$newContent += "                        stats={stats}"
$newContent += "                        recentActivity={recentActivity}"
$newContent += "                        products={products}"
$newContent += "                        getImageUrl={getImageUrl}"
$newContent += "                        setActiveSection={setActiveSection}"
$newContent += "                        fetchData={fetchData}"
$newContent += "                    />"
$newContent += "                );"
$newContent += "        }"
$newContent += "    };"
$newContent += $lines[$endLine..($lines.Length-1)]
Set-Content $filePath $newContent
